# Generated by Django 5.2.11 on 2026-05-18 19:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('nivel', models.CharField(choices=[('Informativo', 'Informativo (Azul)'), ('Atencao', 'Atenção (Amarelo)'), ('Critico', 'Crítico (Vermelho)')], default='Informativo', max_length=15)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField(help_text='Data até quando o alerta deve aparecer na tela')),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmpresaParceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=20)),
                ('responsavel', models.CharField(blank=True, max_length=100, null=True)),
                ('site_ou_rede_social', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='agendacoleta',
            options={},
        ),
        migrations.RemoveField(
            model_name='bairro',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='tiporesiduo',
            name='ativo',
        ),
        migrations.RemoveField(
            model_name='tiporesiduo',
            name='cor_hex',
        ),
        migrations.RemoveField(
            model_name='tiporesiduo',
            name='data_cadastro',
        ),
        migrations.AddField(
            model_name='bairro',
            name='regiao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tiporesiduo',
            name='cor_identificacao',
            field=models.CharField(blank=True, default='#888888', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='tiporesiduo',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendacoleta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='agendacoleta',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro'),
        ),
        migrations.AlterField(
            model_name='agendacoleta',
            name='data_cadastro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='agendacoleta',
            name='dia_semana',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='agendacoleta',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.tiporesiduo'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tiporesiduo',
            name='nome',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='OcorrenciaZeladoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_problema', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ocorrencias/')),
                ('status', models.CharField(choices=[('Aberto', 'Aberto/Pendente'), ('Analise', 'Em Análise pela Prefeitura'), ('Resolvido', 'Resolvido/Concluído')], default='Aberto', max_length=15)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.bairro')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cidadão')),
            ],
        ),
        migrations.CreateModel(
            name='PontoColetaVoluntaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('ponto_referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bairro')),
                ('tipos_aceitos', models.ManyToManyField(to='app.tiporesiduo')),
            ],
        ),
    ]
