# Generated by Django 5.2.11 on 2026-06-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alertacidade_empresaparceira_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontocoletavoluntaria',
            name='tipos_aceitos',
        ),
        migrations.AddField(
            model_name='agendacoleta',
            name='rua',
            field=models.CharField(blank=True, default='Geral / Todas as Ruas', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pontocoletavoluntaria',
            name='types_aceitos',
            field=models.ManyToManyField(to='app.tiporesiduo'),
        ),
    ]
