# Generated by Django 5.2.11 on 2026-06-08 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_pontocoletavoluntaria_tipos_aceitos_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inscricao_imobiliaria', models.CharField(max_length=20, unique=True, verbose_name='Inscrição Imobiliária (Código)')),
                ('cpf_cnpj', models.CharField(max_length=18, verbose_name='CPF/CNPJ do Titular')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço do Imóvel')),
                ('valor_venal', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Valor Venal (R$)')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Proprietário Cadastrado')),
            ],
        ),
        migrations.CreateModel(
            name='IPTU2026',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.IntegerField(default=2026)),
                ('parcela_numero', models.IntegerField(help_text='0 para Cota Única, 1 a 10 para parcelas normais')),
                ('tipo_cobranca', models.CharField(choices=[('COTA_UNICA', 'Cota Única (Com Desconto)'), ('PARCELA', 'Parcela Mensal')], default='PARCELA', max_length=15)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto / Aguardando'), ('PAGO', 'Pago / Compensado'), ('VENCIDO', 'Vencido')], default='ABERTO', max_length=15)),
                ('linha_digitavel', models.CharField(blank=True, max_length=50, null=True, verbose_name='Linha Digitável do Boleto')),
                ('codigo_pix', models.TextField(blank=True, null=True, verbose_name='Copia e Cola PIX da Prefeitura')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debitos', to='app.imovel')),
            ],
        ),
        migrations.CreateModel(
            name='Manifestacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocolo', models.CharField(editable=False, max_length=8, unique=True)),
                ('tipo', models.CharField(choices=[('RECLAMACAO', 'Reclamação'), ('DENUNCIA', 'Denúncia'), ('SUGESTAO', 'Sugestão'), ('ELOGIO', 'Elogio')], default='RECLAMACAO', max_length=15)),
                ('assunto', models.CharField(max_length=100)),
                ('descricao', models.TextField(verbose_name='Descrição do Fato')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente de Análise'), ('EM_ANDAMENTO', 'Em Andamento'), ('RESOLVIDO', 'Resolvido')], default='PENDENTE', max_length=15)),
                ('resposta_admin', models.TextField(blank=True, null=True, verbose_name='Resposta da Ouvidoria')),
                ('bairro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.bairro', verbose_name='Bairro Ocorrido')),
            ],
        ),
    ]
