# Generated by Django 5.2.11 on 2026-06-08 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_manifestacao_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendamentoCataTreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco_completo', models.CharField(max_length=255, verbose_name='Endereço de Recolhimento')),
                ('descricao_itens', models.TextField(help_text='Ex: 1 sofá velho e 1 geladeira quebrada')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_agendada', models.DateField(blank=True, null=True, verbose_name='Data Marcada para Recolhimento')),
                ('status', models.CharField(choices=[('AGUARDANDO', 'Aguardando Aprovação'), ('AGENDADO', 'Coleta Agendada'), ('RECOLHIDO', 'Material Recolhido'), ('CANCELADO', 'Cancelado')], default='AGUARDANDO', max_length=15)),
                ('observacoes_prefeitura', models.TextField(blank=True, null=True, verbose_name='Notas da Zeladoria')),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.bairro', verbose_name='Bairro de Retirada')),
                ('cidadao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cidadão Solicitante')),
            ],
            options={
                'verbose_name': 'Agendamento Cata-Treco',
                'verbose_name_plural': 'Agendamentos Cata-Treco',
            },
        ),
        migrations.CreateModel(
            name='RegistroColetaRealizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_execucao', models.DateField(verbose_name='Data da Coleta')),
                ('horario_registro', models.DateTimeField(auto_now_add=True, verbose_name='Hora do Registro')),
                ('motorista_ou_equipe', models.CharField(blank=True, max_length=100, null=True, verbose_name='Equipe/Caminhão')),
                ('ocorrencia_na_rota', models.CharField(blank=True, help_text='Ex: Rota concluída com atraso devido à chuva / Carro obstruindo via', max_length=255, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.agendacoleta', verbose_name='Rota da Agenda')),
            ],
            options={
                'verbose_name': 'Registro de Coleta Realizada',
                'verbose_name_plural': 'Registros de Coletas Realizadas',
                'ordering': ['-horario_registro'],
            },
        ),
    ]
